### PR TITLE
added support to SET2 card

### PR DESCRIPTION
**Pull request by zuckberj**
Hey, I've almost completed added the SET2 card, but I can't get what I'm missing for the xref thing to be functional.

### CODE REVIEW

**Comment by SteveDoyle2** [comment]
Sets are a bit special in how they're done.  What references the SET2 card?  For example, the SET1 card is used by the SPLINE1 card, so it's called as:

    def cross_reference(self, model: BDF) -> None:
        """
        Cross links the card so referenced cards can be extracted directly

        Parameters
        ----------
        model : BDF()
            the BDF object

        """
        msg = ', which is required by SPLINE1 eid=%s' % self.eid
        self.caero_ref = model.CAero(self.caero, msg=msg)
        self.setg_ref = model.Set(self.setg, msg=msg)  #  <-------- the SET1/SET3; does a SET2 even work for SPLINE1?
        self.setg_ref.cross_reference_set(model, 'Node', msg=msg)

        nnodes = len(self.setg_ref.ids)
        if nnodes < 3:
            msg = 'SPLINE1 requires at least 3 nodes; nnodes=%s\n' % (nnodes)
            msg += str(self)
            msg += str(self.setg_ref)
            raise RuntimeError(msg)


The SET1 cross reference can either reference nodes or elements, so:

    def cross_reference_set(self, model, xref_type, msg='', allow_empty_nodes=False):
        """
        Cross links the card so referenced cards can be extracted directly

        Parameters
        ----------
        model : BDF()
            the BDF object
        xref_type : str
            {'Node', 'Point'}
        allow_empty_nodes : bool; default=False
            do all nodes need to exist?

        SPLINEx, ACMODL, PANEL, AECOMP, XYOUTPUT

        - nodes
          - SPLINEx (all nodes must exist)
          - PANEL (all nodes must exist)
          - XYOUTPUT (missing nodes ignored)
          - AECOMP
          - ACMODL (optional)
        - elements
          - ACMODL (optional)

        """
        msg = ', which is required by SET1 sid=%s%s' % (self.sid, msg)
        if xref_type == 'Node':
            self.ids_ref = model.Nodes(self.get_ids(), msg=msg)
        elif xref_type == 'Point':
            self.ids_ref = model.Points(self.get_ids(), msg=msg)
        else:
            raise NotImplementedError("xref_type=%r and must be ['Node', 'Point']" % xref_type)
        self.xref_type = xref_type

**Comment by zuckberj** [comment]
Other thing that I didn't get, when the function
```python
def cross_reference(self, model: BDF) -> None:
```
is supposed to be call? So the `cross_reference_set()` can be triggered.

I've saw some tests as sample, and the `cross_reference()` function is explicitly called. I thought that has somehow called in a kinda automatic way.

**Comment by SteveDoyle2** [comment]
> Other thing that I didn't get, when the function 

> def cross_reference(self, model: BDF) -> None:
is supposed to be call? So the cross_reference_set() can be triggered.

It's called during ``read_bdf(xref=True)``.  You can also set that to False and call ``cross_reference()`` explicitly (e.g., if you want to modify things first).

As long as the SET2 reference the CAERO, I think it should be good.

**Comment by zuckberj** [comment]
There was a problem with the PAERO5 card, the 9th field of the first line must be blank, I've fixed that.

So, I think we're all good, I'll check for review. :)

**Comment by SteveDoyle2** [comment]
Good stuff!  Thanks!  Just in time for 1.3

**Pull request merged**
