### PR TITLE
implementation of MSC nastran CFAST element type 126

### PR DESCRIPTION
**Pull request by DerRuffi**
this element is widely used in aircraft industries for fastener modelisation
PS: pynastran is awesome!

### CODE REVIEW

**Comment by SteveDoyle2** [comment]
It looks like there's a bug regarding MSC vs. NX Nastran.  MSC's CFAST is element type 126, but the NX CFAST element is 119 (it's a CSEAM for MSC).  I don't have a modern MSC Nastran, so I need an example for that.

**Comment by DerRuffi** [comment]
Hi Steve,
Thank you for your quick response.
I have uploaded a small test model and op2, which was run with MSC Nastran 2015.
Here the link:
[Link to model](https://www.dropbox.com/s/jd4x215usuwuv3z/test_model_CFAST.tar.gz?dl=0)
Let me know if I can assist. 
Kind regards,
Niklas

**Comment by DerRuffi** [comment]
In case you have no dropbox, here he files in my Fork:
https://github.com/DerRuffi/pyNastran/tree/master/models/msc

**Comment by SteveDoyle2** [comment]
I feel bad for never replying.  I made some changes to my local branch and was having trouble merging your changes, so I decided to just copy and paste them from your branch to mine.  I also added the test files (and made a test), as well as fixing a BDF bug for the CFAST.  It's all incorporated now.  There is a RealCFastForceArrayNX and RealCFastForceArrayMSC now.  The MSC version looks like a CBUSH, while the NX version looks like a CBAR...

By chance do you have an output for the F06?  The F06 writer is not currently supported for the MSC CFAST.

**Comment by DerRuffi** [comment]
Hi Steven,

 

Sure, I have the f06. I will upload tomorrow, when I have access to my files.

Don't feel bad!

I can tell you that pyNastran is more and more used by developers inside my company, because it allows to by-pass all that commercial stuff, allowing tailored software for specific jobs.

Keep on going!

 

Greetings from Hamburg, Germany.

Niklas

 

 
 

Gesendet: Samstag, 15. Februar 2020 um 07:46 Uhr
Von: "Steven Doyle" <notifications@github.com>
An: SteveDoyle2/pyNastran <pyNastran@noreply.github.com>
Cc: "Niklas Freeman" <ruffryderniklas@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [SteveDoyle2/pyNastran] implementation of MSC nastran CFAST element type 126 (#588)


I feel bad for never replying. I made some changes to my local branch and was having trouble merging your changes, so I decided to just copy and paste them from your branch to mine. I also added the test files (and made a test), as well as fixing a BDF bug for the CFAST. It's all incorporated now. There is a RealCFastForceArrayNX and RealCFastForceArrayMSC now. The MSC version looks like a CBUSH, while the NX version looks like a CBAR...

By chance do you have an output for the F06? The F06 writer is not currently supported for the MSC CFAST.

**Comment by DerRuffi** [comment]
f06 file is now uploaded here:
https://github.com/DerRuffi/pyNastran/tree/master/models/msc

**Pull request closed without merging**
