### PR TITLE
Small robustness improvements

### PR DESCRIPTION
**Pull request by saullocastro**

### CODE REVIEW

**Comment by saullocastro** [comment]
Dear @SteveDoyle2 , please let me know what you think about this pull request.

**Comment by SteveDoyle2** [comment]
I'm not totally sure on the case you're trying to handle with "checking if bool(nid)==True, this makes it work for models with CFAST defined as Prop-Prop".  Is it just the blank nodes on the CQUAD8 case (which was apparently already mentioned, but doesn't really look like it was handled properly)?

Regarding "ENH: assuming thetarad=0 if bdf does not contain these op2 eids", what case is that?  There are shell elements that don't have an mcid, but do have a theta.  I'm also not totally clear as to the data types on those array, but I think it's a float.  If it's an integer, it needs to be projected onto the element.  

I can't tell if the float case is handled (it looks like there is a projection being done, but no check for float data).  Can you add a note regarding that?  I don't care so much about if it's not totally complete, but just that it's clear in what it can do.

**Comment by saullocastro** [comment]
@SteveDoyle2  sorry for the late reply.

In some of our models the CFASTs are defined using two properties (prop-prop) and for those cases  the current PyNastran code fails. We just had to add a check `if nid` to prevent `nid_to_eids_map[None]`.

The other part of the commit was important because it happened we had op2 files created with the full model and we used a residual model as the input bdf for PyNastran when transforming the coordinates to the material direction. Since some elements did not exist in the residual model, ` vecthetarad = np.array([thetarad[eid] for eid in veceids])` failed but not ` vecthetarad = np.array([thetarad.get(eid, 0) for eid in veceids])` would use a null theta angle instead of causing errors. The best would be to have op2 files storing the material direction for the elements.

I did not enderstand what you suggested me to do in order to change this pull request. Could you please be more detailed?

Regards
Saullo

**Comment by SteveDoyle2** [comment]
No worries.  I just want to make sure things are clear and since you wrote it :)

I'm not totally up on residual structure, so I'll defer to you on that.  Can you add something like:

    # some elements don't exist for the residual structure model, so we assume theta=0.0
    vecthetarad = np.array([thetarad.get(eid, 0) 

>  The best would be to have op2 files storing the material direction for the elements.

It's supposed to, but I'd need to see an example.  The OP2 can be weird about defining duplicate node/element ids that are actually different.  I never really understood why as the Nastran TPL examples aren't exactly well documented.  That might be the reason.

Regarding CFASTs, do you have an example of the CFAST issue?

Regarding the change, on line 199:

    csysi = np.array([bdf.coords[e.thetaMcid].i for e in quadelems])

This only supports mcid elements correct (e.g. not theta)?  Is that correct?  What I was requesting was a note in the docstring along the lines of `handles shell mcid/theta field` or `only handles shell mcid field`.

**Comment by saullocastro** [comment]
@SteveDoyle2  Regarding your note on `csysi`, there is currently support for either `MCID` or `THETA`. We use masked indexing to separate elements with MCID from those with THETA (see the `mcid` array). I added a remark on the docstring.

If you want to check if the op2 has data regarding the material angle THETA for each 2D element, you can use the op2 files in: 

https://github.com/SteveDoyle2/pyNastran/tree/master/pyNastran/op2/test/test_dummy_wing_metallic, 
https://github.com/SteveDoyle2/pyNastran/tree/master/pyNastran/op2/test/test_flat_plate_composite
or
https://github.com/SteveDoyle2/pyNastran/tree/master/pyNastran/op2/test/test_flat_plate_metallic

**Comment by saullocastro** [comment]
@SteveDoyle2  I will try to prepare a model with CFAST so you can have a look. Thanks!

**Comment by saullocastro** [comment]
Dear @SteveDoyle2. I prepared a model using CFAST defined using two properties.
Please, see the updated pull request.

If you import this model and run `get_node_id_to_element_ids_map()` using the current master repository you get the following error:

`In [3]: mesh.get_node_id_to_element_ids_map()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-9fab38940353> in <module>()
----> 1 mesh.get_node_id_to_element_ids_map()

C:\repos\pyNastran\pyNastran\bdf\bdf_interface\get_card.pyc in get_node_id_to_element_ids_map(self)
    523             else:
    524                 for nid in nids:  # (e.g. CQUAD8 with missing node)
--> 525                     nid_to_eids_map[nid].append(eid)
    526
    527         return nid_to_eids_map

KeyError: None`

**Comment by SteveDoyle2** [comment]
Good stuff.  Thanks!

**Pull request merged**
