### PR TITLE
TST: fixing tests

### PR DESCRIPTION
**Pull request by saullocastro**
Fixing tests for coordinate transformation of complex stresses

### CODE REVIEW

**Comment by saullocastro** [comment]
@SteveDoyle2  I need help here...  do you know what is the error

```
======================================================================
ERROR: test_force (pyNastran.op2.test.examples.test_op2_in_material_coord_panel_SOL_108.TestMaterialCoordComplex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/test/examples/test_op2_in_material_coord_panel_SOL_108.py", line 36, in test_force
    op2.read_op2(os.path.join(basepath, prefix + '.op2'))
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/op2.py", line 394, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=op2_filename)
    table_names = self._read_tables(table_name)
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/op2_interface/op2_scalar.py", line 1679, in _read_tables
    self._read_results_table()
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/op2_interface/op2_scalar.py", line 3180, in _read_results_table
    self._read_subtables()
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/fortran_format.py", line 380, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/fortran_format.py", line 431, in _read_subtable_3_4
    n = self._read_subtable_results(table4_parser, record_len)
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/fortran_format.py", line 552, in _read_subtable_results
    n = table4_parser(data, ndata)
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/tables/oes_stressStrain/oes.py", line 241, in _read_oes1_4
    n = self._read_oes1_4_sort1(data, ndata)
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/tables/oes_stressStrain/oes.py", line 421, in _read_oes1_4_sort1
    n = self._read_oes1_loads(data, ndata)
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/tables/oes_stressStrain/oes.py", line 918, in _read_oes1_loads
    _result_name, _class_obj = self.get_stress_mapper()
  File "/home/travis/build/saullocastro/pyNastran/pyNastran/op2/tables/oes_stressStrain/oes.py", line 855, in get_stress_mapper
    return stress_mapper[self.element_type, self.format_code, self.num_wide, self.table_name]
KeyError: (144, 3, 77, b'OES1X')
```

**Comment by SteveDoyle2** [comment]
That is weird that you didn't see it brfore.

The error is just a really bad way to say that that combination has never been tested.  For some reason Nastran will spit out OES1, OES1X, OES1X1, OES1C, and a few other stress tables.  I was trying to figure out the pattern.  Composites are OES1C.  That's all I know for sure. 

 I can do that one and finally fix that hortible message.

**Comment by SteveDoyle2** [comment]
Alright...It's closer.

There's still a problem with 'panel_SOL_108_corner'.  

Based on the the following:
    
    cquad4_force[1]
      type=ComplexPlate2ForceArray ntimes=21 nelements=35
      eType
      data: [ntimes, nnodes, 8] where 8=[mx, my, mxy, bmx, bmy, bmxy, tx, ty]
      data.shape = (21, 175, 8)
      element name: QUAD144 (corner)
      sort1
      freqs = [  1.    1.5   2.  ...,  10.   10.5  11. ]

    ---------------------------------------------------------------------

    cquad4_force[1]
      type=ComplexPlateForceArray ntimes=21 nelements=35
      eType
      data: [ntimes, nnodes, 8] where 8=[mx, my, mxy, bmx, bmy, bmxy, tx, ty]
      data.shape = (21, 35, 8)
      element name: CQUAD4 (center)
      sort1
      freqs = [  1.    1.5   2.  ...,  10.   10.5  11. ]

For CQUAD4 center results (element_type=33), there is 1 output location for each of the 35 elements, with a total number of rows as 35 rows.

For CQUAD4 corner results (element_type=144), strangely it's 175 (35*5 nodes) instead of 35*10.  I'm not sure if that's a bug on my end or not...

        F:\work\pyNastran\pyNastran\master4\pyNastran\op2\test\examples>python test_op2_in_material_coord_panel_SOL_108.py TestMaterialCoordComplex.test_force
    WARNING: data_in_material_coord.py:269 force neids = 35
    WARNING: data_in_material_coord.py:270 force Sxy.shape = (21, 175)
    WARNING: data_in_material_coord.py:271 vecthetarad.shape = (35,)
    ERROR:   test_op2_in_material_coord_panel_SOL_108.py:44 failed rotating 'panel_SOL_108_corner'
    E
    ======================================================================
    ERROR: test_force (__main__.TestMaterialCoordComplex)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test_op2_in_material_coord_panel_SOL_108.py", line 42, in test_force
        op2_new = data_in_material_coord(bdf, op2)
      File "f:\work\pynastran\pynastran\master4\pyNastran\op2\data_in_material_coord.py", line 272, in data_in_material_coord
        Sxx_theta_real, Syy_theta_real, Sxy_theta_real = transf_Mohr(Sxx.real, Syy.real, Sxy.real, vecthetarad)
      File "f:\work\pynastran\pynastran\master4\pyNastran\op2\data_in_material_coord.py", line 44, in transf_Mohr
        thetarad_Mohr = np.arctan2(-Sxy, Sxx - Scenter) + 2*thetarad
    ValueError: operands could not be broadcast together with shapes (21,175) (35,)

**Comment by saullocastro** [comment]
@SteveDoyle2  all right. I will perform more tests here. I don't think your code has a problem with corner outputs since the tests for real stresses already consider cases with corner outputs.

**Pull request merged**
