### PR TITLE
ENH: get_edges for LineElements and RodElement

### PR DESCRIPTION
**Pull request by saullocastro**
I've seen the importance of an Edge object such as:

    class Edge(object):
        def __init__(self):
            self.nodes = set()
            self.elements = set()

to check the connectivity among elements in an algorithm like:

    # Finding edges
    mesh.edges = []
    for element in mesh.elements.values():
        el_edges = element.get_edges()
        for nodes in el_edges:
            nodes = set(nodes)
            is_new_edge = True
            for edge in mesh.edges:
                if nodes == edge.nodes:
                    is_new_edge = False
                    break
            if is_new_edge:
                new_edge = Edge()
                new_edge.nodes = set(nodes)
                new_edge.elements.add(element)
                mesh.edges.append(new_edge)
            else:
                edge.elements.add(element)

But for this approach to work the `LineElement` and `RodElement` should also have the method `get_edges` implemented, which is conceptually correct.

In this pull request I'm suggesting to add such methods.

If there is interest we could think of making this algorithm for edge detection shown above a new pull request.

### CODE REVIEW

**Comment by SteveDoyle2** [comment]
I've definitely implemented methods like that in the past.  

Looks good.

**Comment by saullocastro** [comment]
@SteveDoyle2  I was showing to my colleague how to contribute to pyNastran when I realized that the authorship of my commits has been lost, it appears as an "unknown" user. Check here

https://github.com/SteveDoyle2/pyNastran/commit/a2823015ece578f2e0f3a1a6051351c8c559b9ad

for an example. Do you know what could it be?

**Comment by SteveDoyle2** [comment]
After googling...

Per https://github.com/isaacs/github/issues/168

Did you delete your pyNastran fork?

Another possibility is you haven't linked your email address to your
account.

**Comment by saullocastro** [comment]
Hi Steve. I've configured my local repository and now I assume it will keep
track of the authorship!

Thanks for the answer...


2015-06-12 19:21 GMT-03:00 SteveDoyle2 <notifications@github.com>:

**Comment by SteveDoyle2** [comment]
@saullocastro I got a question about the get_edges method.  I've been doing some of my own work with edges at work and I think we want to change this to use self.node_ids to avoid making the edges a tuple of node objects when you cross reference.  Thoughts/concerns?

**Comment by saullocastro** [comment]
From my point of view the tuple also does the job...

**Comment by SteveDoyle2** [comment]
Alright.  I'll add a get_edge_ids method.  Thanks for the feedback.

**Comment by saullocastro** [comment]
I'm afraid I didn't understand... are you going to build the method to
detect and store the edges for each node/element? Or just the method to get
the node_ids?

2015-06-18 14:57 GMT-03:00 SteveDoyle2 <notifications@github.com>:

**Comment by SteveDoyle2** [comment]
For a CTRIA3, the get_edges method is:

    def get_edges(self):
        """
        Returns the edges
        """
        return [(self.nodes[0], self.nodes[1]),
                (self.nodes[1], self.nodes[2]),
                (self.nodes[2], self.nodes[0])]

For xref=False, self.nodes[0] is an integer.  For xref=True, self.nodes[0]
is a GRID object.  Using this method...

    def get_edge_ids(self):
        """
        Return the edge IDs
        """
        node_ids = self.node_ids
        return [(node_ids[0], node_ids[1]),
                (node_ids[1], node_ids[2]),
                (node_ids[2], node_ids[0])]

node_ids[0] is always an integer.

The data will not be stored on the element.  It's just a get method.

My question was did you think the "get_edges" method is valuable given the
limitation?  It's technically faster for xref=False at least to get the
edges (maybe not when using them given the additional overhead), but more
error prone.

**Comment by saullocastro** [comment]
I understand your intention now.... It would be nice to have a class Edge
with the methods "elements" and "nodes" to have multiple cross-reference
possibilities:  element -> edges  node -> edges   edge -> elements
 edge -> nodes ...

2015-06-18 15:47 GMT-03:00 SteveDoyle2 <notifications@github.com>:

**Comment by SteveDoyle2** [comment]
I'm not totally following.  I work with edges as follows:

    eid_to_edge_map = defaultdict(list)
    edge_to_eid_map = defaultdict(list)
    for eid, element in iteritems(self.model.elements):
        # I make each edge a sorted tuple so the +edge and -edge doesn't
matter
        edges = element.get_edge_ids()
        for edge in edges:
            edge_to_eid_map.append(eid)
        eid_to_edge_map = edges

I typically use that to extract the free edges of a model, which is useful
in finding holes in what should be a watertight shell model.

I think a edge_to_nid_map & nid_to_edge_map are useful in rarer cases.  One
example is you want to cut a shell model through a bunch of CQUAD4s and
make a ring of CONROD elements that define the plane.  You can find the
cutting plane nodes, know that they're mapped to an edge, and then map that
to an element.  From there you do something like ring the elements and
extract the cut area for each ring of elements.

What are your use cases?

**Comment by saullocastro** [comment]
My main use case is a routine to find panels with cutouts (free edges). I
do an additional check which is to find if there are coincident elements in
each panel... I will try with your approach because it seems much faster
(prevent building many cross-references)... I will let you know!


2015-06-18 16:37 GMT-03:00 SteveDoyle2 <notifications@github.com>:

**Pull request merged**
