### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by josiahlund**
The only non-trivial update in this is a change in the hyperlink to the installation instructions. I changed the link to point to the latest documentation so that a manual update to the readme (for this link) is not required any time the version number is changed.

### CODE REVIEW

**Comment by SteveDoyle2** [comment]
Can you revert the "Change install instructions link to latest" commit?  That's in the section "Installation from Release" and should not point to the latest.

Other than that, good stuff :)

**Comment by josiahlund** [comment]
I certainly can, but I was actually curious why the link pointed to the installation from release section of the install instructions and not just the higher level install instructions (https://pynastran-git.readthedocs.io/en/latest/installation/installation.html#).

I've been reading my way through The Pragmatic Programmer and one thing that I felt personally attacked by was the part that covered writing things in a way that is "Easy to change". In trying to dig in to the documentation and getting involved with this, it's been difficult to follow and even find the right documentation. Knowing that the documentation for 1.4 exists has been helpful, but I had to URL guess (easy enough to do) to find the 1.4 documentation. Unless I'm missing something all of the links to documentation point to documentation for the 1.3 release.

Having documentation or links that need to be updated with each release seems really cumbersome and error prone. Is there a reason the latest documentation couldn't serve all versions?

**Comment by SteveDoyle2** [comment]
So generally, releases don't take too long, but latest more or less is 1.4.  The docs for "latest" are accessible through the button at the top of https://github.com/SteveDoyle2/pyNastran.  You can also go to readthedocs and select the pulldown at the bottom to get to 1.4.

I guess I totally agree that there could be a cleaner way, but in a sense, I'm in too deep.  It's hard to tell what is unclear to someone new given that it's more or less like that since I wrote the docs.  Beyond that, I think the biggest challenge is having a reasonable structure.  I find the layout to be confusing and am not really sure to control the formatting any better.  The screenshot below is just kind of a mess.

image

As to your question regarding merging things, I'm not opposed to that.  I do think the install section is about 2x too long.  Installation has gotten easier over the years thanks to pip, but the GUI can still be hard to setup.

**Comment by josiahlund** [comment]
I'm certainly guilty of not being able to take off the "expert" goggles and look at things from a newcomers perspective. I've managed to get everything installed (including the GUI, which wasn't actually too much trouble (praise pip)) so let me get my bearings a bit and I will **try** to give the documentation a full overhaul so that it makes sense to me, a newcomer. Not to figure out to to revert my commit and press forward with this MR.

**Comment by SteveDoyle2** [comment]
The easiest way is to just push a new one :)

I'm an engineer who happens to code.  I took a CS course in high school ~21
years ago.  I know what a UML diagram is, but couldn't do one off the top
of my head.  I assume most people using pyNastran are in that boat.

**Comment by josiahlund** [comment]
In the future I'll try to remember to use a dedicated branch instead of my master branch for any pull requests. I'm actually much more adept at rewriting git history than is probably typical for a non-CS person. I've screwed up many a personal repository and have sunk hours (if not days) in figuring out how to recover. I resisted the urge to rebase without that commit and force push over my repo.

My only formal programming training was in C in 2012, but I have since picked up python and found it tremendously helpful in chewing through large amounts of data. A couple of years ago I made the shift from Patran to HyperMesh and it's very much a love/hate relationship. I like a lot of the tools and layout but it's got a lot of bugs. Since I can't pull back the curtain on HM, I wanted to make my own pre/post processor from scratch, but figured it's be much easier (and beneficial to all) to piggy back on somebody else's work.

**Comment by josiahlund** [comment]
Can I get a status update on this?

**Comment by SteveDoyle2** [comment]
I thought you were going to update it.  I'll pull it and update it.

**Pull request merged**
