### PR TITLE
Fix cMethods typo

### PR DESCRIPTION
**Pull request by Msegade**

### CODE REVIEW

**Comment by SteveDoyle2** [comment]
Why is this a typo?

In bdf/bdf_interface/attributes.py, I see:
        self.cMethods = {}  # type: Dict[int, Any]

**Comment by Msegade** [comment]
Because it is written cmethods, not cMethods. Sorry if I'm missing something obvious here.

**Comment by SteveDoyle2** [comment]
Maybe I'm missing something, but why?

If it's going to change, it needs to be changed in all the places where it's used.

**Comment by Msegade** [comment]
If I define a complex methods in subcase 1 in my BDF file like this: 
`EIGC,1,HESS,MAX,,12`
and I read the BDF using pynastran with: 
`model = BDF()`
`model.read_bdf(bdf_filename)`
when I try to get the values using the CMethod method:
`model.CMethods(1)`
I get the error 
`AttributeError: 'BDF' object has no attribute 'cmethods'`
Because as you pointed out, the attribute its defined as  'cMethods'. 
So changing the name to 'cMethods' in the 'get_methods.py' file 
(it is correct in other parts of the code), solves the issue.

**Comment by Msegade** [comment]
As I don't understand why you closed this. Can you please explain why this simple test fails? (I'm using one of the .bdfs in the models folder)

[test.zip](https://github.com/SteveDoyle2/pyNastran/files/2619258/test.zip)

**Comment by SteveDoyle2** [comment]
I don't see the message I just typed, so...

I ran your example and wow...my mistake.  I completely misread that pull request.

I thought you changed the variable name from `cMethods` to `cmethods` and not the other way around.

**Comment by Msegade** [comment]
Ok, glad is now solved.

**Pull request merged**
